services:
  - type: web
    name: sasstech-symfony-app
    env: docker
    plan: free
    region: frankfurt # Change as needed
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
