services:
  - type: web
    name: sasstech-symfony-app
    env: docker
    plan: free
    region: frankfurt # Change as needed
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sasstech-db
          property: connectionString

databases:
  - name: sasstech-db
    plan: free
    databaseName: sasstech_db
    user: sasstech_user
    region: frankfurt # Ensure it matches web service
